# Imports

In [ ]:
pip install PyPDF2

Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)

In [ ]:
pip install pdfminer.six

Requirement already satisfied: pdfminer.six in /usr/local/lib/python3.12/dist-packages (20251107)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six) (2.23)

In [ ]:
pip install pdfplumber

Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.8)
Requirement already satisfied: pdfminer.six==20251107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251107)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (4.30.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)

In [ ]:
pip install pdf2image

Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from pdf2image) (11.3.0)

In [ ]:
pip install Pillow

Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)

In [ ]:
# 1. Базовые
!pip install pandas tqdm openpyxl textdistance pdf2image pillow pytesseract pdfplumber PyPDF2

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.1)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Collecting textdistance
  Downloading textdistance-4.6.3-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pdf2image in /usr/local/lib/python3.12/dist-packages (1.17.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (11.3.0)
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.8)
Requirement already satisfied: PyPDF2 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from pytesseract) (25.0)
Requirement already satisfied: pdfminer.six==20251107 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251107)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.0.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251107->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading textdistance-4.6.3-py3-none-any.whl (31 kB)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: textdistance, pytesseract
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pytesseract]
Successfully installed pytesseract-0.3.13 textdistance-4.6.3

In [ ]:
# 2. Остальные OCR
!pip install easyocr paddleocr docling  # docling тянет PyMuPDF+torch

Collecting easyocr
  Downloading easyocr-1.7.2-py3-none-any.whl.metadata (10 kB)
Collecting paddleocr
  Downloading paddleocr-3.3.2-py3-none-any.whl.metadata (55 kB)
Collecting docling
  Downloading docling-2.62.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.8.0+cu126)
Requirement already satisfied: torchvision>=0.5 in /usr/local/lib/python3.12/dist-packages (from easyocr) (0.23.0+cu126)
Requirement already satisfied: opencv-python-headless in /usr/local/lib/python3.12/dist-packages (from easyocr) (4.12.0.88)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from easyocr) (1.16.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.3.5)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from easyocr) (11.3.0)
Requirement already satisfied: scikit-image in /usr/local/lib/python3.12/dist-packages (from easyocr) (0.25.2)
Collecting python-bidi (from easyocr)
  Downloading python_bidi-0.6.7-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from easyocr) (6.0.3)
Requirement already satisfied: Shapely in /usr/local/lib/python3.12/dist-packages (from easyocr) (2.1.2)
Collecting pyclipper (from easyocr)
  Downloading pyclipper-1.3.0.post6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.0 kB)
Collecting ninja (from easyocr)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting paddlex<3.4.0,>=3.3.0 (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading paddlex-3.3.9-py3-none-any.whl.metadata (79 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from paddleocr) (2.32.4)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from paddleocr) (4.15.0)
Collecting aistudio-sdk>=0.3.5 (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading aistudio_sdk-0.3.8-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: chardet in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (5.2.0)
Collecting colorlog (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (3.20.0)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (0.36.0)
Collecting modelscope>=1.28.0 (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading modelscope-1.32.0-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (25.0)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2.2.2)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (3.16.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (9.0.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2.11.10)
Collecting PyYAML (from easyocr)
  Downloading PyYAML-6.0.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting ruamel.yaml (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading ruamel.yaml-0.18.16-py3-none-any.whl.metadata (25 kB)
Collecting ujson (from paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading ujson-5.11.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (9.4 kB)
Requirement already satisfied: imagesize in /usr/local/lib/python3.12/dist-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (1.4.1)
Collecting opencv-contrib-python==4.10.0.84 (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading opencv_contrib_python-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: pypdfium2>=4 in /usr/local/lib/python3.12/dist-packages (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (5.0.0)
Collecting docling-core<3.0.0,>=2.50.1 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading docling_core-2.51.1-py3-none-any.whl.metadata (7.6 kB)
Collecting docling-parse<5.0.0,>=4.7.0 (from docling)
  Downloading docling_parse-4.7.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting docling-ibm-models<4,>=3.9.1 (from docling)
  Downloading docling_ibm_models-3.10.2-py3-none-any.whl.metadata (7.3 kB)
Collecting filetype<2.0.0,>=1.2.0 (from docling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting pypdfium2>=4 (from paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from docling) (2.12.0)
Collecting rapidocr<4.0.0,>=3.3 (from docling)
  Downloading rapidocr-3.4.2-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from docling) (2025.10.5)
Collecting rtree<2.0.0,>=1.3.0 (from docling)
  Downloading rtree-1.4.1-py3-none-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Collecting typer<0.20.0,>=0.12.5 (from docling)
  Downloading typer-0.19.2-py3-none-any.whl.metadata (16 kB)
Collecting python-docx<2.0.0,>=1.1.2 (from docling)
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting python-pptx<2.0.0,>=1.0.2 (from docling)
  Downloading python_pptx-1.0.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.12.3 in /usr/local/lib/python3.12/dist-packages (from docling) (4.13.5)
Collecting marko<3.0.0,>=2.1.2 (from docling)
  Downloading marko-2.2.1-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: openpyxl<4.0.0,>=3.1.5 in /usr/local/lib/python3.12/dist-packages (from docling) (3.1.5)
Requirement already satisfied: lxml<7.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from docling) (5.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from docling) (4.67.1)
Requirement already satisfied: pluggy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from docling) (1.6.0)
Collecting pylatexenc<3.0,>=2.10 (from docling)
  Downloading pylatexenc-2.10.tar.gz (162 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate<2,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from docling) (1.11.0)
Collecting polyfactory>=2.22.2 (from docling)
  Downloading polyfactory-3.0.0-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling) (5.9.5)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from accelerate<2,>=1.0.0->docling) (0.6.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.12.3->docling) (2.8)
Requirement already satisfied: jsonschema<5.0.0,>=4.16.0 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling) (4.25.1)
Collecting jsonref<2.0.0,>=1.1.0 (from docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading jsonref-1.1.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.9.0)
Collecting latex2mathml<4.0.0,>=3.77.0 (from docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading latex2mathml-3.78.1-py3-none-any.whl.metadata (15 kB)
Collecting semchunk<3.0.0,>=2.2.0 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading semchunk-2.2.2-py3-none-any.whl.metadata (10 kB)
Collecting tree-sitter<1.0.0,>=0.23.2 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter-0.25.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Collecting tree-sitter-python<1.0.0,>=0.23.6 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter_python-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (1.9 kB)
Collecting tree-sitter-c<1.0.0,>=0.23.4 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter_c-0.24.1-cp310-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting tree-sitter-java<1.0.0,>=0.23.5 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter_java-0.23.5-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting tree-sitter-javascript<1.0.0,>=0.23.1 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter_javascript-0.25.0-cp310-abi3-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (2.2 kB)
Collecting tree-sitter-typescript<1.0.0,>=0.23.2 (from docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading tree_sitter_typescript-0.23.2-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.3 kB)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.12/dist-packages (from docling-core[chunking]<3.0.0,>=2.50.1->docling) (4.51.0)
Collecting jsonlines<5.0.0,>=3.1.0 (from docling-ibm-models<4,>=3.9.1->docling)
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonlines<5.0.0,>=3.1.0->docling-ibm-models<4,>=3.9.1->docling) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.16.0->docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.16.0->docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema<5.0.0,>=4.16.0->docling-core<3.0.0,>=2.50.1->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.28.0)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl<4.0.0,>=3.1.5->docling) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.3.0->docling) (1.2.1)
Collecting XlsxWriter>=0.5.7 (from python-pptx<2.0.0,>=1.0.2->docling)
  Downloading xlsxwriter-3.2.9-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: opencv-python>=4.5.1.48 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.3->docling) (4.12.0.88)
Requirement already satisfied: six>=1.15.0 in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.3->docling) (1.17.0)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (from rapidocr<4.0.0,>=3.3->docling) (2.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->paddleocr) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->paddleocr) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->paddleocr) (2.5.0)
Collecting mpire[dill] (from semchunk<3.0.0,>=2.2.0->docling-core[chunking]<3.0.0,>=2.50.1->docling)
  Downloading mpire-2.10.2-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch->easyocr) (3.4.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.34.0->docling-core[chunking]<3.0.0,>=2.50.1->docling) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.34.0->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.21.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.20.0,>=0.12.5->docling) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.20.0,>=0.12.5->docling) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.20.0,>=0.12.5->docling) (13.9.4)
Collecting bce-python-sdk (from aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading bce_python_sdk-0.9.52-py3-none-any.whl.metadata (416 bytes)
Collecting numpy (from easyocr)
  Downloading numpy-2.2.6-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting faker>=5.0.0 (from polyfactory>=2.22.2->docling)
  Downloading faker-38.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<0.20.0,>=0.12.5->docling) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->typer<0.20.0,>=0.12.5->docling) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.20.0,>=0.12.5->docling) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->easyocr) (1.3.0)
Collecting pycryptodome>=3.8.0 (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr)
  Downloading pycryptodome-3.23.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
Requirement already satisfied: future>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from bce-python-sdk->aistudio-sdk>=0.3.5->paddlex<3.4.0,>=3.3.0->paddlex[ocr-core]<3.4.0,>=3.3.0->paddleocr) (1.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->easyocr) (3.0.3)
Requirement already satisfied: multiprocess>=0.70.15 in /usr/local/lib/python3.12/dist-packages (from mpire[dill]->semchunk<3.0.0,>=2.2.0->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.70.16)
Requirement already satisfied: dill>=0.3.8 in /usr/local/lib/python3.12/dist-packages (from multiprocess>=0.70.15->mpire[dill]->semchunk<3.0.0,>=2.2.0->docling-core[chunking]<3.0.0,>=2.50.1->docling) (0.3.8)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from omegaconf->rapidocr<4.0.0,>=3.3->docling) (4.9.3)

In [ ]:
!pip install surya-ocr

Collecting surya-ocr
  Downloading surya_ocr-0.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: click<9.0.0,>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (8.3.0)
Requirement already satisfied: einops<0.9.0,>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (0.8.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (1.2.0)
Collecting opencv-python-headless==4.11.0.86 (from surya-ocr)
  Downloading opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pillow<11.0.0,>=10.2.0 (from surya-ocr)
  Downloading pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: platformdirs<5.0.0,>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (4.5.0)
Collecting pre-commit<5.0.0,>=4.2.0 (from surya-ocr)
  Downloading pre_commit-4.4.0-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.11.10)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.12.0)
Requirement already satisfied: pypdfium2==4.30.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (4.30.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (1.2.1)
Requirement already satisfied: torch<3.0.0,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.8.0+cu126)
Collecting transformers>=4.56.1 (from surya-ocr)
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from opencv-python-headless==4.11.0.86->surya-ocr) (2.2.6)
Collecting cfgv>=2.0.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Downloading cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting identify>=1.0.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Downloading identify-2.6.15-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting nodeenv>=0.11.1 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Downloading nodeenv-1.9.1-py2.py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (6.0.2)
Collecting virtualenv>=20.10.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Downloading virtualenv-20.35.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.4.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0.0,>=2.7.0->surya-ocr) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (25.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (2.32.4)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=4.56.1->surya-ocr)
  Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.56.1->surya-ocr) (1.2.0)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.10.0->pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Downloading distlib-0.4.0-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0.0,>=2.7.0->surya-ocr) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (2025.10.5)
Downloading surya_ocr-0.17.0-py3-none-any.whl (183 kB)
Downloading opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 MB 35.0 MB/s  0:00:01
Downloading pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 71.6 MB/s  0:00:00
Downloading pre_commit-4.4.0-py2.py3-none-any.whl (226 kB)
Downloading cfgv-3.5.0-py2.py3-none-any.whl (7.4 kB)
Downloading identify-2.6.15-py2.py3-none-any.whl (99 kB)
Downloading nodeenv-1.9.1-py2.py3-none-any.whl (22 kB)
Downloading transformers-4.57.1-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 79.0 MB/s  0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 53.7 MB/s  0:00:00
Downloading virtualenv-20.35.4-py3-none-any.whl (6.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 41.5 MB/s  0:00:00
Downloading distlib-0.4.0-py2.py3-none-any.whl (469 kB)
ERROR: Operation cancelled by user

In [ ]:
!pip install surya-ocr

Collecting surya-ocr
  Using cached surya_ocr-0.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: click<9.0.0,>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (8.3.0)
Requirement already satisfied: einops<0.9.0,>=0.8.1 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (0.8.1)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (1.2.0)
Collecting opencv-python-headless==4.11.0.86 (from surya-ocr)
  Using cached opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pillow<11.0.0,>=10.2.0 (from surya-ocr)
  Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: platformdirs<5.0.0,>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (4.5.0)
Collecting pre-commit<5.0.0,>=4.2.0 (from surya-ocr)
  Using cached pre_commit-4.4.0-py2.py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.11.10)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.12.0)
Requirement already satisfied: pypdfium2==4.30.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (4.30.0)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (1.2.1)
Requirement already satisfied: torch<3.0.0,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from surya-ocr) (2.8.0+cu126)
Collecting transformers>=4.56.1 (from surya-ocr)
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.12/dist-packages (from opencv-python-headless==4.11.0.86->surya-ocr) (2.2.6)
Collecting cfgv>=2.0.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Using cached cfgv-3.5.0-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting identify>=1.0.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Using cached identify-2.6.15-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting nodeenv>=0.11.1 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Using cached nodeenv-1.9.1-py2.py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit<5.0.0,>=4.2.0->surya-ocr) (6.0.2)
Collecting virtualenv>=20.10.0 (from pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Using cached virtualenv-20.35.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.5.3->surya-ocr) (0.4.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch<3.0.0,>=2.7.0->surya-ocr) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3.0.0,>=2.7.0->surya-ocr) (1.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (0.36.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (25.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (2.32.4)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers>=4.56.1->surya-ocr)
  Using cached tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.56.1->surya-ocr) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=4.56.1->surya-ocr) (1.2.0)
Collecting distlib<1,>=0.3.7 (from virtualenv>=20.10.0->pre-commit<5.0.0,>=4.2.0->surya-ocr)
  Using cached distlib-0.4.0-py2.py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3.0.0,>=2.7.0->surya-ocr) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=4.56.1->surya-ocr) (2025.10.5)
Using cached surya_ocr-0.17.0-py3-none-any.whl (183 kB)
Using cached opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (50.0 MB)
Using cached pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl (4.5 MB)
Using cached pre_commit-4.4.0-py2.py3-none-any.whl (226 kB)
Using cached cfgv-3.5.0-py2.py3-none-any.whl (7.4 kB)
Using cached identify-2.6.15-py2.py3-none-any.whl (99 kB)
Using cached nodeenv-1.9.1-py2.py3-none-any.whl (22 kB)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Using cached tokenizers-0.22.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached virtualenv-20.35.4-py3-none-any.whl (6.0 MB)
Using cached distlib-0.4.0-py2.py3-none-any.whl (469 kB)
Installing collected packages: distlib, virtualenv, pillow, opencv-python-headless, nodeenv, identify, cfgv, pre-commit, tokenizers, transformers, surya-ocr
   ━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/11 [virtualenv]ERROR: Operation cancelled by user
^C

In [ ]:
pip install paddlepaddle -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

In [ ]:
!pip install "python-doctr[torch]"

In [ ]:
!pip install olmocr  # требует torch>=2.1

In [ ]:
!pip install llmwhisperer-client

In [ ]:
!pip install transformers>=4.40 flash-attn --no-build-isolation  # для Qwen2.5-VL

In [ ]:
!apt-get update -qq && apt-get install -y poppler-utils

In [ ]:
# ставим сам tesseract + русский язык
!apt-get update -qq && apt-get install -y tesseract-ocr tesseract-ocr-rus

In [ ]:
pip install gliner

Requirement already satisfied: gliner in /usr/local/lib/python3.12/dist-packages (0.2.22)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from gliner) (2.8.0+cu126)
Requirement already satisfied: transformers<=4.51.0,>=4.38.2 in /usr/local/lib/python3.12/dist-packages (from gliner) (4.51.0)
Requirement already satisfied: huggingface_hub>=0.21.4 in /usr/local/lib/python3.12/dist-packages (from gliner) (0.36.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gliner) (4.67.1)
Requirement already satisfied: onnxruntime in /usr/local/lib/python3.12/dist-packages (from gliner) (1.23.2)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from gliner) (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<=4.51.0,>=4.38.2->gliner) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.21.4->gliner) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->gliner) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->gliner) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->gliner) (3.0.3)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (15.0.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (25.9.23)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime->gliner) (5.29.5)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.12/dist-packages (from coloredlogs->onnxruntime->gliner) (10.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.51.0,>=4.38.2->gliner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.51.0,>=4.38.2->gliner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.51.0,>=4.38.2->gliner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<=4.51.0,>=4.38.2->gliner) (2025.10.5)

In [ ]:
# ставим сам spaCy (если ещё не стоит)
!pip install -U spacy

# скачиваем русскую большую модель
!python -m spacy download ru_core_news_lg

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.8)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.2)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.11.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Collecting ru-core-news-lg==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/ru_core_news_lg-3.8.0/ru_core_news_lg-3.8.0-py3-none-any.whl (513.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 513.4/513.4 MB 20.9 MB/s  0:00:19
Requirement already satisfied: pymorphy3>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ru-core-news-lg==3.8.0) (2.0.6)
Requirement already satisfied: dawg2-python>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from pymorphy3>=1.0.0->ru-core-news-lg==3.8.0) (0.9.0)
Requirement already satisfied: pymorphy3-dicts-ru in /usr/local/lib/python3.12/dist-packages (from pymorphy3>=1.0.0->ru-core-news-lg==3.8.0) (2.4.417150.4580142)
Requirement already satisfied: setuptools>=68.2.2 in /usr/local/lib/python3.12/dist-packages (from pymorphy3>=1.0.0->ru-core-news-lg==3.8.0) (80.9.0)
✔ Download and installation successful
You can now load the package via spacy.load('ru_core_news_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

# OCR

Источники для OCR

[Semantic Understanding And Contextual Explanation
of Medical Documents](https://www.sciencexcel.com/articles/XPPkael9emNJWlZqXj29XbRkz7QsSqxcCU4Cj7R6.pdf)

[Deep learning-based NLP data pipeline for EHR-scanned document information extraction](https://pmc.ncbi.nlm.nih.gov/articles/PMC9188320/)

[Best Open-Source OCR Tools in 2025: A Comparison](https://unstract.com/blog/best-opensource-ocr-tools-in-2025/)

[Современные OCR для сложных документов](https://habr.com/ru/articles/966846/)

In [ ]:
import os, time, textdistance, pandas as pd, json, csv
from pathlib import Path
from tqdm import tqdm
from pdf2image import convert_from_path
from PIL import Image
import pytesseract

PDF_DIR   = "/content/med"
CACHE_DIR = Path("/content/ocr_cache")
CACHE_DIR.mkdir(exist_ok=True)
DETAIL_CSV = "/content/detail.csv"
REPORT_XLSX = "/content/report.xlsx"

def baseline_pdf(pdf_path):
    images = convert_from_path(pdf_path, dpi=300)
    return '\n'.join(pytesseract.image_to_string(im, lang='rus') for im in images)

# ---------- метрики ----------
def metrics(a, b):
    cer = textdistance.levenshtein(a, b) / max(len(a), 1)
    return {"cer": round(cer, 4),
            "len_b": len(b),
            "pipes_b": b.count('|'),
            "badchars_b": b.count('�')}

# ---------- универсальный обработчик ----------
def run_ocr(ocr_name, ocr_func, pdf_files, is_pdf_level):
    """
    ocr_func - вызывается либо с pdf_path, либо с PIL.Image
    is_pdf_level - True для docling/doctr/olmocr/whisperer, False для остальных
    """
    rows = []
    for pdf in tqdm(pdf_files, desc=ocr_name):
        stem = pdf.stem
        baseline_text = baseline_pdf(pdf)
        t0 = time.time()
        if is_pdf_level:
            text = ocr_func(pdf)
        else:
            images = convert_from_path(pdf, dpi=300)
            text = '\n'.join(ocr_func(im) for im in images)
        elapsed = time.time() - t0
        m = metrics(baseline_text, text)
        rows.append({"file": stem,
                     f"{ocr_name}_cer": m["cer"],
                     f"{ocr_name}_len": m["len_b"],
                     f"{ocr_name}_pipes": m["pipes_b"],
                     f"{ocr_name}_badchars": m["badchars_b"],
                     f"{ocr_name}_time": round(elapsed, 2)})
    # дозаписываем в csv
    df_new = pd.DataFrame(rows).set_index("file")
    if Path(DETAIL_CSV).exists():
        df_old = pd.read_csv(DETAIL_CSV).set_index("file")
        df_old = df_old.join(df_new, how="outer")
    else:
        df_old = df_new
    df_old.reset_index().to_csv(DETAIL_CSV, index=False)
    print(f"[{ocr_name}] сохранено {len(rows)} строк")
    return df_new

# ---------- список PDF ----------
pdf_files = list(Path(PDF_DIR).glob("*.pdf"))
print(f"Найдено {len(pdf_files)} PDF")

Найдено 2 PDF

In [ ]:
# ================== 1. Tesseract  ==================
# %% tesseract
def tesseract_page(pil_im):
    return pytesseract.image_to_string(pil_im, lang='rus')

run_ocr("tesseract", tesseract_page, pdf_files, False)

tesseract: 100%|██████████| 2/2 [04:20<00:00, 130.32s/it]

[tesseract] сохранено 2 строк

,tesseract_cer,tesseract_len,tesseract_pipes,tesseract_badchars,tesseract_time
file,,,,,
шаблон мед карты,0.0,11543,5,0,63.04
шаблон-мед-карты,0.0,11717,4,0,66.44

In [ ]:
# ================== 2. EasyOCR ==================
# %% easyocr
def easyocr_page(pil_im):
    import easyocr, numpy as np
    if not hasattr(easyocr_page, 'reader'):
        easyocr_page.reader = easyocr.Reader(['ru'])
    return ' '.join(easyocr_page.reader.readtext(np.array(pil_im), detail=0))

run_ocr("easyocr", easyocr_page, pdf_files, False)

easyocr:   0%|          | 0/2 [00:00<?, ?it/s]WARNING:easyocr.easyocr:Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
easyocr:  50%|█████     | 1/2 [22:39<22:39, 1359.27s/it]/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:666: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
easyocr: 100%|██████████| 2/2 [44:53<00:00, 1346.58s/it]

[easyocr] сохранено 2 строк

,easyocr_cer,easyocr_len,easyocr_pipes,easyocr_badchars,easyocr_time
file,,,,,
шаблон мед карты,0.1820,10380,0,0,1295.81
шаблон-мед-карты,0.1983,10382,0,0,1268.36

In [ ]:
# ================== 3. Docling ==================
# %% docling
def docling_pdf(pdf_path):
    from docling.document_converter import DocumentConverter

    if not hasattr(docling_pdf, 'conv'):
        docling_pdf.conv = DocumentConverter()
    result = docling_pdf.conv.convert(pdf_path)
    return result.document.export_to_markdown()

run_ocr("docling", docling_pdf, pdf_files, True)

docling:   0%|          | 0/2 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
docling: 100%|██████████| 2/2 [07:12<00:00, 216.49s/it]

[docling] сохранено 2 строк

,docling_cer,docling_len,docling_pipes,docling_badchars,docling_time
file,,,,,
шаблон мед карты,2.0327,31845,379,0,165.33
шаблон-мед-карты,2.2324,34728,418,0,137.43

In [ ]:
# ================== 4. Surya ==================

def surya_page(pil_im):
    from surya.detection import DetectionPredictor
    from surya.recognition import RecognitionPredictor
    from surya.foundation import FoundationPredictor

    # Инициализируем один раз
    if not hasattr(surya_page, 'det_predictor'):
        surya_page.det_predictor = DetectionPredictor()
        foundation = FoundationPredictor()
        surya_page.rec_predictor = RecognitionPredictor(foundation)

    # Распознаём
    preds = surya_page.rec_predictor([pil_im], det_predictor=surya_page.det_predictor)
    # preds — список из одного элемента (т.к. передали 1 картинку)
    return ' '.join(line.text for line in preds[0].text_lines)

run_ocr("surya", surya_page, pdf_files, False)

surya:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading manifest.json: 100%|██████████| 127/127 [00:00<00:00, 109kB/s]

Downloading text_detection model to /root/.cache/datalab/models/text_detection/2025_05_07:   0%|          | 0/6 [00:00<?, ?it/s]

Downloading preprocessor_config.json: 100%|██████████| 373/373 [00:00<00:00, 589kB/s]




Downloading training_args.bin:   0%|          | 0.00/5.49k [00:00<?, ?B/s]


Downloading README.md:   0%|          | 0.00/393 [00:00<?, ?B/s]

Downloading training_args.bin: 100%|██████████| 5.49k/5.49k [00:00<00:00, 445kB/s]
Downloading README.md: 100%|██████████| 393/393 [00:00<00:00, 31.4kB/s]




Downloading .gitattributes: 100%|██████████| 1.48k/1.48k [00:00<00:00, 1.13MB/s]



Downloading config.json: 100%|██████████| 858/858 [00:00<00:00, 1.24MB/s]


Downloading model.safetensors:  25%|██▍       | 18.0M/73.4M [00:00<00:00, 183MB/s]

Downloading model.safetensors:  44%|████▎     | 32.0M/73.4M [00:00<00:00, 162MB/s]

Downloading model.safetensors:  65%|██████▌   | 48.0M/73.4M [00:00<00:00, 162MB/s]

Downloading model.safetensors: 100%|██████████| 73.4M/73.4M [00:00<00:00, 171MB/s]

Downloading text_detection model to /root/.cache/datalab/models/text_detection/2025_05_07: 100%|██████████| 6/6 [00:00<00:00, 11.50it/s]

Downloading manifest.json: 100%|██████████| 262/262 [00:00<00:00, 310kB/s]

Downloading text_recognition model to /root/.cache/datalab/models/text_recognition/2025_09_23:   0%|          | 0/12 [00:00<?, ?it/s]

Downloading .gitattributes: 100%|██████████| 1.48k/1.48k [00:00<00:00, 2.24MB/s]




Downloading vocab_math.json:   0%|          | 0.00/20.1k [00:00<?, ?B/s]

Downloading README.md:   0%|          | 0.00/5.05k [00:00<?, ?B/s]


Downloading specials_dict.json:   0%|          | 0.00/43.5k [00:00<?, ?B/s]




Downloading vocab_math.json: 100%|██████████| 20.1k/20.1k [00:00<00:00, 659kB/s]
Downloading specials_dict.json: 100%|██████████| 43.5k/43.5k [00:00<00:00, 2.79MB/s]






Downloading special_tokens_map.json: 100%|██████████| 278/278 [00:00<00:00, 388kB/s]
Downloading training_args.bin: 100%|██████████| 7.45k/7.45k [00:00<00:00, 364kB/s]







Downloading README.md: 100%|██████████| 5.05k/5.05k [00:00<00:00, 101kB/s]


Downloading tokenizer_config.json: 100%|██████████| 694/694 [00:00<00:00, 443kB/s]



Downloading preprocessor_config.json:   0%|          | 0.00/419 [00:00<?, ?B/s]
Downloading config.json: 100%|██████████| 50.2k/50.2k [00:00<00:00, 4.32MB/s]




Downloading specials.json: 100%|██████████| 19.6k/19.6k [00:00<00:00, 31.7MB/s]
Downloading preprocessor_config.json: 100%|██████████| 419/419 [00:00<00:00, 54.1kB/s]





Downloading processor_config.json: 100%|██████████| 411/411 [00:00<00:00, 130kB/s]


Downloading model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Downloading model.safetensors:   1%|          | 8.00M/1.34G [00:00<00:17, 82.0MB/s]

Downloading model.safetensors:   1%|          | 15.0M/1.34G [00:00<00:18, 76.8MB/s]

Downloading model.safetensors:   2%|▏         | 23.0M/1.34G [00:00<00:18, 78.6MB/s]

Downloading model.safetensors:   2%|▏         | 28.0M/1.34G [00:00<00:21, 66.0MB/s]

Downloading model.safetensors:   2%|▏         | 33.0M/1.34G [00:00<00:23, 60.4MB/s]

Downloading model.safetensors:   3%|▎         | 40.0M/1.34G [00:00<00:22, 63.1MB/s]

Downloading model.safetensors:   3%|▎         | 48.0M/1.34G [00:00<00:20, 67.4MB/s]

Downloading model.safetensors:   4%|▍         | 53.0M/1.34G [00:00<00:22, 61.9MB/s]

Downloading model.safetensors:   4%|▍         | 59.0M/1.34G [00:00<00:22, 60.2MB/s]

Downloading model.safetensors:   5%|▍         | 65.0M/1.34G [00:01<00:23, 59.4MB/s]

Downloading model.safetensors:   5%|▌         | 71.0M/1.34G [00:01<00:23, 58.4MB/s]

Downloading model.safetensors:   6%|▌         | 76.0M/1.34G [00:01<00:24, 56.4MB/s]

Downloading model.safetensors:   6%|▌         | 83.0M/1.34G [00:01<00:23, 57.5MB/s]

Downloading model.safetensors:   6%|▋         | 86.0M/1.34G [00:01<00:27, 49.9MB/s]

Downloading model.safetensors:   7%|▋         | 91.0M/1.34G [00:01<00:27, 48.6MB/s]

Downloading model.safetensors:   7%|▋         | 96.0M/1.34G [00:01<00:27, 49.4MB/s]

Downloading model.safetensors:   7%|▋         | 101M/1.34G [00:01<00:27, 48.0MB/s]

Downloading model.safetensors:   8%|▊         | 105M/1.34G [00:01<00:28, 46.0MB/s]

Downloading model.safetensors:   8%|▊         | 110M/1.34G [00:02<00:30, 43.8MB/s]

Downloading model.safetensors:   8%|▊         | 114M/1.34G [00:02<00:30, 42.7MB/s]

Downloading model.safetensors:   9%|▊         | 119M/1.34G [00:02<00:29, 44.4MB/s]

Downloading model.safetensors:   9%|▉         | 124M/1.34G [00:02<00:29, 44.9MB/s]

Downloading model.safetensors:  10%|▉         | 131M/1.34G [00:02<00:25, 51.9MB/s]

Downloading model.safetensors:  10%|▉         | 137M/1.34G [00:02<00:23, 54.7MB/s]

Downloading model.safetensors:  10%|█         | 143M/1.34G [00:02<00:22, 56.9MB/s]

Downloading model.safetensors:  11%|█         | 149M/1.34G [00:02<00:22, 57.8MB/s]

Downloading model.safetensors:  11%|█▏        | 156M/1.34G [00:02<00:20, 60.9MB/s]

Downloading model.safetensors:  12%|█▏        | 162M/1.34G [00:03<00:21, 59.6MB/s]

Downloading model.safetensors:  12%|█▏        | 169M/1.34G [00:03<00:20, 60.1MB/s]

Downloading model.safetensors:  13%|█▎        | 177M/1.34G [00:03<00:19, 65.9MB/s]

Downloading model.safetensors:  13%|█▎        | 184M/1.34G [00:03<00:18, 65.9MB/s]

Downloading model.safetensors:  14%|█▍        | 193M/1.34G [00:03<00:17, 71.8MB/s]

Downloading model.safetensors:  15%|█▍        | 199M/1.34G [00:03<00:19, 62.5MB/s]

Downloading model.safetensors:  15%|█▍        | 205M/1.34G [00:03<00:20, 58.6MB/s]

Downloading model.safetensors:  15%|█▌        | 211M/1.34G [00:03<00:20, 58.7MB/s]

Downloading model.safetensors:  16%|█▌        | 219M/1.34G [00:03<00:20, 60.1MB/s]

Downloading model.safetensors:  17%|█▋        | 227M/1.34G [00:04<00:18, 63.6MB/s]

Downloading model.safetensors:  17%|█▋        | 234M/1.34G [00:04<00:19, 61.5MB/s]

Downloading model.safetensors:  18%|█▊        | 241M/1.34G [00:04<00:19, 62.1MB/s]

Downloading model.safetensors:  18%|█▊        | 246M/1.34G [00:04<00:20, 58.8MB/s]

Downloading model.safetensors:  19%|█▊        | 254M/1.34G [00:04<00:20, 58.3MB/s]

Downloading model.safetensors:  19%|█▉        | 262M/1.34G [00:04<00:18, 63.4MB/s]

Downloading model.safetensors:  20%|█▉        | 270M/1.34G [00:04<00:17, 66.9MB/s]

Downloading model.safetensors:  20%|██        | 277M/1.34G [00:04<00:17, 63.9MB/s]

Downloading model.safetensors:  21%|██        | 284M/1.34G [00:05<00:17, 65.4MB/s]

Downloading model.safetensors:  21%|██        | 291M/1.34G [00:05<00:17, 65.8MB/s]

Downloading model.safetensors:  22%|██▏       | 299M/1.34G [00:05<00:15, 70.7MB/s]

Downloading model.safetensors:  22%|██▏       | 305M/1.34G [00:05<00:16, 66.3MB/s]

Downloading model.safetensors:  23%|██▎       | 310M/1.34G [00:05<00:18, 61.2MB/s]

Downloading model.safetensors:  23%|██▎       | 315M/1.34G [00:05<00:19, 57.9MB/s]

Downloading model.safetensors:  23%|██▎       | 320M/1.34G [00:05<00:21, 52.1MB/s]

Downloading model.safetensors:  24%|██▎       | 324M/1.34G [00:05<00:22, 48.6MB/s]

Downloading model.safetensors:  24%|██▍       | 329M/1.34G [00:05<00:22, 48.6MB/s]

Downloading model.safetensors:  24%|██▍       | 335M/1.34G [00:06<00:20, 51.9MB/s]

Downloading model.safetensors:  25%|██▍       | 341M/1.34G [00:06<00:20, 53.6MB/s]

Downloading model.safetensors:  25%|██▌       | 349M/1.34G [00:06<00:18, 57.8MB/s]

Downloading model.safetensors:  26%|██▌       | 356M/1.34G [00:06<00:19, 55.7MB/s]

Downloading model.safetensors:  26%|██▋       | 362M/1.34G [00:06<00:18, 57.4MB/s]

Downloading model.safetensors:  27%|██▋       | 369M/1.34G [00:06<00:18, 58.4MB/s]

Downloading model.safetensors:  27%|██▋       | 376M/1.34G [00:06<00:17, 58.5MB/s]

Downloading model.safetensors:  28%|██▊       | 380M/1.34G [00:06<00:19, 53.3MB/s]

Downloading model.safetensors:  28%|██▊       | 388M/1.34G [00:06<00:17, 59.4MB/s]

Downloading model.safetensors:  29%|██▊       | 394M/1.34G [00:07<00:17, 58.6MB/s]

Downloading model.safetensors:  29%|██▉       | 398M/1.34G [00:07<00:18, 54.0MB/s]

Downloading model.safetensors:  30%|██▉       | 405M/1.34G [00:07<00:17, 57.5MB/s]

Downloading model.safetensors:  30%|███       | 412M/1.34G [00:07<00:16, 61.9MB/s]

Downloading model.safetensors:  30%|███       | 418M/1.34G [00:07<00:17, 56.2MB/s]

Downloading model.safetensors:  31%|███       | 423M/1.34G [00:07<00:18, 53.4MB/s]

Downloading model.safetensors:  31%|███       | 427M/1.34G [00:07<00:19, 49.7MB/s]

Downloading model.safetensors:  32%|███▏      | 433M/1.34G [00:07<00:18, 52.2MB/s]

Downloading model.safetensors:  32%|███▏      | 441M/1.34G [00:07<00:16, 57.8MB/s]

Downloading model.safetensors:  33%|███▎      | 446M/1.34G [00:08<00:17, 54.6MB/s]

Downloading model.safetensors:  33%|███▎      | 453M/1.34G [00:08<00:16, 58.6MB/s]

Downloading model.safetensors:  34%|███▎      | 461M/1.34G [00:08<00:15, 62.9MB/s]

Downloading model.safetensors:  34%|███▍      | 466M/1.34G [00:08<00:16, 58.7MB/s]

Downloading model.safetensors:  34%|███▍      | 470M/1.34G [00:08<00:18, 52.1MB/s]

Downloading model.safetensors:  35%|███▍      | 475M/1.34G [00:08<00:18, 51.7MB/s]

Downloading model.safetensors:  35%|███▌      | 482M/1.34G [00:08<00:16, 56.4MB/s]

Downloading model.safetensors:  35%|███▌      | 485M/1.34G [00:08<00:19, 48.7MB/s]

Downloading model.safetensors:  36%|███▌      | 489M/1.34G [00:08<00:21, 43.0MB/s]

Downloading model.safetensors:  36%|███▌      | 495M/1.34G [00:09<00:20, 46.0MB/s]

Downloading model.safetensors:  37%|███▋      | 501M/1.34G [00:09<00:19, 47.4MB/s]

Downloading model.safetensors:  37%|███▋      | 506M/1.34G [00:09<00:20, 44.7MB/s]

Downloading model.safetensors:  37%|███▋      | 512M/1.34G [00:09<00:18, 48.6MB/s]

Downloading model.safetensors:  38%|███▊      | 515M/1.34G [00:09<00:20, 43.1MB/s]

Downloading model.safetensors:  38%|███▊      | 520M/1.34G [00:09<00:21, 41.5MB/s]

Downloading model.safetensors:  38%|███▊      | 524M/1.34G [00:09<00:24, 36.0MB/s]

Downloading model.safetensors:  38%|███▊      | 527M/1.34G [00:10<00:29, 29.7MB/s]

Downloading model.safetensors:  39%|███▊      | 531M/1.34G [00:10<00:29, 30.1MB/s]

Downloading model.safetensors:  39%|███▉      | 537M/1.34G [00:10<00:23, 37.6MB/s]

Downloading model.safetensors:  39%|███▉      | 541M/1.34G [00:10<00:23, 37.9MB/s]

Downloading model.safetensors:  40%|███▉      | 546M/1.34G [00:10<00:21, 40.1MB/s]

Downloading model.safetensors:  40%|████      | 551M/1.34G [00:10<00:20, 41.9MB/s]

Downloading model.safetensors:  40%|████      | 554M/1.34G [00:10<00:22, 38.7MB/s]

Downloading model.safetensors:  41%|████      | 557M/1.34G [00:10<00:24, 35.6MB/s]

Downloading model.safetensors:  41%|████      | 559M/1.34G [00:10<00:27, 30.5MB/s]

Downloading model.safetensors:  41%|████      | 561M/1.34G [00:11<00:32, 26.1MB/s]

Downloading model.safetensors:  41%|████▏     | 568M/1.34G [00:11<00:22, 38.3MB/s]

Downloading model.safetensors:  42%|████▏     | 575M/1.34G [00:11<00:18, 46.3MB/s]

Downloading model.safetensors:  42%|████▏     | 581M/1.34G [00:11<00:16, 50.6MB/s]

Downloading model.safetensors:  43%|████▎     | 588M/1.34G [00:11<00:15, 54.1MB/s]

Downloading model.safetensors:  43%|████▎     | 594M/1.34G [00:11<00:15, 52.2MB/s]

Downloading model.safetensors:  44%|████▎     | 599M/1.34G [00:11<00:15, 51.3MB/s]

Downloading model.safetensors:  44%|████▍     | 605M/1.34G [00:11<00:14, 53.8MB/s]

Downloading model.safetensors:  45%|████▍     | 611M/1.34G [00:11<00:14, 54.1MB/s]

Downloading model.safetensors:  45%|████▌     | 618M/1.34G [00:12<00:13, 57.5MB/s]

Downloading model.safetensors:  45%|████▌     | 620M/1.34G [00:12<00:17, 46.2MB/s]

Downloading model.safetensors:  45%|████▌     | 621M/1.34G [00:12<00:23, 33.5MB/s]

Downloading model.safetensors:  46%|████▌     | 629M/1.34G [00:12<00:17, 45.6MB/s]

Downloading model.safetensors:  46%|████▋     | 635M/1.34G [00:12<00:15, 48.5MB/s]

Downloading model.safetensors:  47%|████▋     | 642M/1.34G [00:12<00:14, 52.9MB/s]

Downloading model.safetensors:  47%|████▋     | 649M/1.34G [00:12<00:13, 55.6MB/s]

Downloading model.safetensors:  48%|████▊     | 657M/1.34G [00:12<00:12, 62.2MB/s]

Downloading model.safetensors:  48%|████▊     | 664M/1.34G [00:12<00:11, 65.1MB/s]

Downloading model.safetensors:  49%|████▉     | 672M/1.34G [00:13<00:10, 70.3MB/s]

Downloading model.safetensors:  49%|████▉     | 679M/1.34G [00:13<00:10, 68.0MB/s]

Downloading model.safetensors:  50%|████▉     | 686M/1.34G [00:13<00:10, 66.1MB/s]

Downloading model.safetensors:  51%|█████     | 696M/1.34G [00:13<00:09, 76.6MB/s]

Downloading model.safetensors:  51%|█████     | 703M/1.34G [00:13<00:09, 74.1MB/s]

Downloading model.safetensors:  52%|█████▏    | 709M/1.34G [00:13<00:10, 69.1MB/s]

Downloading model.safetensors:  52%|█████▏    | 713M/1.34G [00:13<00:11, 58.8MB/s]

Downloading model.safetensors:  52%|█████▏    | 718M/1.34G [00:13<00:12, 54.2MB/s]

Downloading model.safetensors:  53%|█████▎    | 723M/1.34G [00:13<00:13, 51.2MB/s]

Downloading model.safetensors:  53%|█████▎    | 726M/1.34G [00:14<00:14, 45.5MB/s]

Downloading model.safetensors:  53%|█████▎    | 731M/1.34G [00:14<00:15, 44.5MB/s]

Downloading model.safetensors:  54%|█████▎    | 736M/1.34G [00:14<00:15, 43.6MB/s]

Downloading model.safetensors:  54%|█████▍    | 740M/1.34G [00:14<00:15, 41.4MB/s]

Downloading model.safetensors:  54%|█████▍    | 743M/1.34G [00:14<00:20, 32.5MB/s]

Downloading model.safetensors:  54%|█████▍    | 747M/1.34G [00:14<00:28, 23.2MB/s]

Downloading model.safetensors:  55%|█████▍    | 748M/1.34G [00:15<00:40, 16.0MB/s]

Downloading model.safetensors:  55%|█████▍    | 751M/1.34G [00:15<00:35, 18.4MB/s]

Downloading model.safetensors:  55%|█████▌    | 759M/1.34G [00:15<00:21, 30.2MB/s]

Downloading model.safetensors:  56%|█████▌    | 767M/1.34G [00:15<00:15, 40.7MB/s]

Downloading model.safetensors:  56%|█████▋    | 774M/1.34G [00:15<00:13, 47.4MB/s]

Downloading model.safetensors:  57%|█████▋    | 780M/1.34G [00:15<00:12, 51.0MB/s]

Downloading model.safetensors:  57%|█████▋    | 786M/1.34G [00:15<00:11, 53.9MB/s]

Downloading model.safetensors:  58%|█████▊    | 791M/1.34G [00:15<00:11, 52.8MB/s]

Downloading model.safetensors:  58%|█████▊    | 796M/1.34G [00:16<00:11, 52.4MB/s]

Downloading model.safetensors:  58%|█████▊    | 802M/1.34G [00:16<00:10, 54.4MB/s]

Downloading model.safetensors:  59%|█████▉    | 810M/1.34G [00:16<00:09, 61.7MB/s]
Downloading text_recognition model to /root/.cache/datalab/models/text_recognition/2025_09_23:  92%|█████████▏| 11/12 [00:16<00:00, 14.47it/s]

Downloading model.safetensors:  60%|█████▉    | 817M/1.34G [00:16<00:09, 64.4MB/s]

Downloading model.safetensors:  60%|██████    | 824M/1.34G [00:16<00:08, 65.3MB/s]

Downloading model.safetensors:  61%|██████    | 832M/1.34G [00:16<00:08, 65.6MB/s]

Downloading model.safetensors:  61%|██████    | 840M/1.34G [00:16<00:08, 66.1MB/s]

Downloading model.safetensors:  62%|██████▏   | 847M/1.34G [00:16<00:08, 66.5MB/s]

Downloading model.safetensors:  62%|██████▏   | 854M/1.34G [00:16<00:08, 65.2MB/s]

Downloading model.safetensors:  63%|██████▎   | 859M/1.34G [00:17<00:08, 61.1MB/s]

Downloading model.safetensors:  63%|██████▎   | 865M/1.34G [00:17<00:08, 61.3MB/s]

Downloading model.safetensors:  64%|██████▎   | 872M/1.34G [00:17<00:08, 61.9MB/s]

Downloading model.safetensors:  64%|██████▍   | 879M/1.34G [00:17<00:08, 60.5MB/s]

Downloading model.safetensors:  64%|██████▍   | 885M/1.34G [00:17<00:08, 59.0MB/s]

Downloading model.safetensors:  65%|██████▍   | 891M/1.34G [00:17<00:08, 56.5MB/s]

Downloading model.safetensors:  65%|██████▌   | 897M/1.34G [00:17<00:08, 55.8MB/s]

Downloading model.safetensors:  66%|██████▌   | 903M/1.34G [00:17<00:09, 54.6MB/s]

Downloading model.safetensors:  66%|██████▌   | 908M/1.34G [00:17<00:09, 53.6MB/s]

Downloading model.safetensors:  67%|██████▋   | 915M/1.34G [00:18<00:08, 55.7MB/s]

Downloading model.safetensors:  67%|██████▋   | 921M/1.34G [00:18<00:08, 57.0MB/s]

Downloading model.safetensors:  68%|██████▊   | 928M/1.34G [00:18<00:07, 60.6MB/s]

Downloading model.safetensors:  68%|██████▊   | 934M/1.34G [00:18<00:07, 59.8MB/s]

Downloading model.safetensors:  69%|██████▊   | 942M/1.34G [00:18<00:06, 65.9MB/s]

Downloading model.safetensors:  69%|██████▉   | 948M/1.34G [00:18<00:06, 64.4MB/s]

Downloading model.safetensors:  70%|██████▉   | 954M/1.34G [00:18<00:06, 62.9MB/s]

Downloading model.safetensors:  70%|███████   | 961M/1.34G [00:18<00:06, 62.3MB/s]

Downloading model.safetensors:  71%|███████   | 968M/1.34G [00:18<00:06, 62.2MB/s]

Downloading model.safetensors:  71%|███████   | 972M/1.34G [00:19<00:08, 51.6MB/s]

Downloading model.safetensors:  71%|███████   | 977M/1.34G [00:19<00:09, 44.5MB/s]

Downloading model.safetensors:  71%|███████▏  | 980M/1.34G [00:19<00:10, 41.1MB/s]

Downloading model.safetensors:  72%|███████▏  | 985M/1.34G [00:19<00:09, 43.7MB/s]

Downloading model.safetensors:  72%|███████▏  | 989M/1.34G [00:19<00:09, 42.8MB/s]

Downloading model.safetensors:  73%|███████▎  | 997M/1.34G [00:19<00:07, 52.9MB/s]

Downloading model.safetensors:  73%|███████▎  | 0.98G/1.34G [00:19<00:07, 53.5MB/s]

Downloading model.safetensors:  74%|███████▎  | 0.99G/1.34G [00:19<00:06, 54.5MB/s]

Downloading model.safetensors:  74%|███████▍  | 0.99G/1.34G [00:20<00:06, 56.0MB/s]

Downloading model.safetensors:  75%|███████▍  | 1.00G/1.34G [00:20<00:06, 60.6MB/s]

Downloading model.safetensors:  75%|███████▌  | 1.01G/1.34G [00:20<00:05, 65.5MB/s]

Downloading model.safetensors:  75%|███████▌  | 1.01G/1.34G [00:20<00:05, 60.2MB/s]

Downloading model.safetensors:  76%|███████▌  | 1.02G/1.34G [00:20<00:06, 54.9MB/s]

Downloading model.safetensors:  76%|███████▋  | 1.02G/1.34G [00:20<00:05, 60.1MB/s]

Downloading model.safetensors:  77%|███████▋  | 1.03G/1.34G [00:20<00:05, 64.9MB/s]

Downloading model.safetensors:  77%|███████▋  | 1.04G/1.34G [00:20<00:05, 60.7MB/s]

Downloading model.safetensors:  78%|███████▊  | 1.04G/1.34G [00:20<00:05, 61.6MB/s]

Downloading model.safetensors:  78%|███████▊  | 1.05G/1.34G [00:20<00:05, 61.8MB/s]

Downloading model.safetensors:  79%|███████▊  | 1.05G/1.34G [00:21<00:04, 61.5MB/s]

Downloading model.safetensors:  79%|███████▉  | 1.06G/1.34G [00:21<00:06, 50.5MB/s]

Downloading model.safetensors:  79%|███████▉  | 1.06G/1.34G [00:21<00:06, 48.1MB/s]

Downloading model.safetensors:  80%|███████▉  | 1.07G/1.34G [00:21<00:05, 53.3MB/s]

Downloading model.safetensors:  80%|████████  | 1.07G/1.34G [00:21<00:05, 51.1MB/s]

Downloading model.safetensors:  81%|████████  | 1.08G/1.34G [00:21<00:05, 52.0MB/s]

Downloading model.safetensors:  81%|████████  | 1.09G/1.34G [00:21<00:04, 55.6MB/s]

Downloading model.safetensors:  82%|████████▏ | 1.10G/1.34G [00:21<00:04, 60.6MB/s]

Downloading model.safetensors:  82%|████████▏ | 1.10G/1.34G [00:22<00:04, 58.4MB/s]

Downloading model.safetensors:  83%|████████▎ | 1.11G/1.34G [00:22<00:03, 63.2MB/s]

Downloading model.safetensors:  83%|████████▎ | 1.11G/1.34G [00:22<00:04, 59.9MB/s]

Downloading model.safetensors:  84%|████████▎ | 1.12G/1.34G [00:22<00:04, 57.2MB/s]

Downloading model.safetensors:  84%|████████▍ | 1.13G/1.34G [00:22<00:03, 67.8MB/s]

Downloading model.safetensors:  85%|████████▍ | 1.14G/1.34G [00:22<00:03, 65.0MB/s]

Downloading model.safetensors:  85%|████████▌ | 1.14G/1.34G [00:22<00:03, 64.8MB/s]

Downloading model.safetensors:  86%|████████▌ | 1.15G/1.34G [00:22<00:03, 65.9MB/s]

Downloading model.safetensors:  86%|████████▋ | 1.16G/1.34G [00:22<00:03, 64.3MB/s]

Downloading model.safetensors:  87%|████████▋ | 1.16G/1.34G [00:23<00:02, 66.2MB/s]

Downloading model.safetensors:  87%|████████▋ | 1.17G/1.34G [00:23<00:02, 66.2MB/s]

Downloading model.safetensors:  88%|████████▊ | 1.18G/1.34G [00:23<00:02, 61.4MB/s]


[surya] сохранено 2 строк

,surya_cer,surya_len,surya_pipes,surya_badchars,surya_time
file,,,,,
шаблон мед карты,0.2733,11036,0,0,3737.25
шаблон-мед-карты,0.2906,11029,0,0,3977.69

In [ ]:
# ================== 5. docTR ==================

def doctr_pdf(pdf_path):
    from doctr.io import DocumentFile
    from doctr.models import ocr_predictor
    if not hasattr(doctr_pdf, 'model'):
        doctr_pdf.model = ocr_predictor(pretrained=True)
    doc = DocumentFile.from_pdf(pdf_path)
    result = doctr_pdf.model(doc)
    return '\n'.join([' '.join(w.value for line in block.lines for w in line.words)
                      for page in result.pages for block in page.blocks])

run_ocr("doctr", doctr_pdf, pdf_files, True)

doctr:   0%|          | 0/2 [00:00<?, ?it/s]

Downloading https://doctr-static.mindee.com/models?id=v0.8.1/fast_base-688a8b34.pt&src=0 to /root/.cache/doctr/models/fast_base-688a8b34.pt

  0%|          | 0/65814772 [00:00<?, ?it/s]

Downloading https://doctr-static.mindee.com/models?id=v0.12.0/crnn_vgg16_bn-0417f351.pt&src=0 to /root/.cache/doctr/models/crnn_vgg16_bn-0417f351.pt

  0%|          | 0/63303144 [00:00<?, ?it/s]

doctr: 100%|██████████| 2/2 [07:50<00:00, 235.42s/it]

[doctr] сохранено 2 строк

,doctr_cer,doctr_len,doctr_pipes,doctr_badchars,doctr_time
file,,,,,
шаблон мед карты,0.8419,10929,0,0,173.29
шаблон-мед-карты,0.8393,10877,0,0,164.88

# NER

Здесь сравниваются методы: re (регулярные выражения), Gliner (трансформер), spacy (state of the art библиотека в nlp)

In [ ]:
# Для считывания PDF
import PyPDF2
# Для анализа структуры PDF и извлечения текста
from pdfminer.high_level import extract_pages, extract_text
from pdfminer.layout import LTTextContainer, LTChar, LTRect, LTFigure
# Для извлечения текста из таблиц в PDF
import pdfplumber
# Для извлечения изображений из PDF
from PIL import Image
from pdf2image import convert_from_path
# Для удаления дополнительно созданных файлов
import os

In [ ]:
# Создаём функцию для извлечения текста

def text_extraction(element):
    # Извлекаем текст из вложенного текстового элемента
    line_text = element.get_text()

    # Находим форматы текста
    # Инициализируем список со всеми форматами, встречающимися в строке текста
    line_formats = []
    for text_line in element:
        if isinstance(text_line, LTTextContainer):
            # Итеративно обходим каждый символ в строке текста
            for character in text_line:
                if isinstance(character, LTChar):
                    # Добавляем к символу название шрифта
                    line_formats.append(character.fontname)
                    # Добавляем к символу размер шрифта
                    line_formats.append(character.size)
    # Находим уникальные размеры и названия шрифтов в строке
    format_per_line = list(set(line_formats))

    # Возвращаем кортеж с текстом в каждой строке вместе с его форматом
    return (line_text, format_per_line)

In [ ]:
# Создаём функцию для вырезания элементов изображений из PDF
def crop_image(element, pageObj):
    # Получаем координаты для вырезания изображения из PDF
    [image_left, image_top, image_right, image_bottom] = [element.x0,element.y0,element.x1,element.y1]
    # Обрезаем страницу по координатам (left, bottom, right, top)
    pageObj.mediabox.lower_left = (image_left, image_bottom)
    pageObj.mediabox.upper_right = (image_right, image_top)
    # Сохраняем обрезанную страницу в новый PDF
    cropped_pdf_writer = PyPDF2.PdfWriter()
    cropped_pdf_writer.add_page(pageObj)
    # Сохраняем обрезанный PDF в новый файл
    with open('cropped_image.pdf', 'wb') as cropped_pdf_file:
        cropped_pdf_writer.write(cropped_pdf_file)

# Создаём функцию для преобразования PDF в изображения
def convert_to_images(input_file,):
    images = convert_from_path(input_file)
    image = images[0]
    output_file = "PDF_image.png"
    image.save(output_file, "PNG")

# Создаём функцию для считывания текста из изображений
def image_to_text(image_path):
    # Считываем изображение
    img = Image.open(image_path)
    # Извлекаем текст из изображения
    text = pytesseract.image_to_string(img)
    return text

In [ ]:
# Извлечение таблиц из страницы

def extract_table(pdf_path, page_num, table_num):
    # Открываем файл pdf
    pdf = pdfplumber.open(pdf_path)
    # Находим исследуемую страницу
    table_page = pdf.pages[page_num]
    # Извлекаем соответствующую таблицу
    table = table_page.extract_tables()[table_num]
    return table

# Преобразуем таблицу в соответствующий формат
def table_converter(table):
    table_string = ''
    # Итеративно обходим каждую строку в таблице
    for row_num in range(len(table)):
        row = table[row_num]
        # Удаляем разрыв строки из текста с переносом
        cleaned_row = [item.replace('\n', ' ') if item is not None and '\n' in item else 'None' if item is None else item for item in row]
        # Преобразуем таблицу в строку
        table_string+=('|'+'|'.join(cleaned_row)+'|'+'\n')
    # Удаляем последний разрыв строки
    table_string = table_string[:-1]
    return table_string

In [ ]:
# Находим путь к PDF
pdf_path = '/content/шаблон мед карты.pdf'

# создаём объект файла PDF
pdfFileObj = open(pdf_path, 'rb')
# создаём объект считывателя PDF
pdfReaded = PyPDF2.PdfReader(pdfFileObj)

# Создаём словарь для извлечения текста из каждого изображения
text_per_page = {}
# Извлекаем страницы из PDF
for pagenum, page in enumerate(extract_pages(pdf_path)):

    # Инициализируем переменные, необходимые для извлечения текста со страницы
    pageObj = pdfReaded.pages[pagenum]
    page_text = []
    line_format = []
    text_from_images = []
    text_from_tables = []
    page_content = []
    # Инициализируем количество исследованных таблиц
    table_num = 0
    first_element= True
    table_extraction_flag= False
    # Открываем файл pdf
    pdf = pdfplumber.open(pdf_path)
    # Находим исследуемую страницу
    page_tables = pdf.pages[pagenum]
    # Находим количество таблиц на странице
    tables = page_tables.find_tables()


    # Находим все элементы
    page_elements = [(element.y1, element) for element in page._objs]
    # Сортируем все элементы по порядку нахождения на странице
    page_elements.sort(key=lambda a: a[0], reverse=True)

    # Находим элементы, составляющие страницу
    for i, component in enumerate(page_elements):
        # Извлекаем положение верхнего края элемента в PDF
        pos = component[0]
        # Извлекаем элемент структуры страницы
        element = component[1]

        # Проверяем, является ли элемент текстовым
        if isinstance(element, LTTextContainer):
            # Проверяем, находится ли текст в таблице
            if table_extraction_flag == False:
                # Используем функцию извлечения текста и формата для каждого текстового элемента
                (line_text, format_per_line) = text_extraction(element)
                # Добавляем текст каждой строки к тексту страницы
                page_text.append(line_text)
                # Добавляем формат каждой строки, содержащей текст
                line_format.append(format_per_line)
                page_content.append(line_text)
            else:
                # Пропускаем текст, находящийся в таблице
                pass

        # Проверяем элементы на наличие изображений
        if isinstance(element, LTFigure):
            # Вырезаем изображение из PDF
            crop_image(element, pageObj)
            # Преобразуем обрезанный pdf в изображение
            convert_to_images('cropped_image.pdf')
            # Извлекаем текст из изображения
            image_text = image_to_text('PDF_image.png')
            text_from_images.append(image_text)
            page_content.append(image_text)
            # Добавляем условное обозначение в списки текста и формата
            page_text.append('image')
            line_format.append('image')

        # Проверяем элементы на наличие таблиц
        if isinstance(element, LTRect):
            # Если первый прямоугольный элемент
            if first_element == True and (table_num + 1) <= len(tables):
                # Находим ограничивающий прямоугольник таблицы
                lower_side = page.bbox[3] - tables[table_num].bbox[3]
                upper_side = element.y1
                # Извлекаем информацию из таблицы
                table = extract_table(pdf_path, pagenum, table_num)
                # Преобразуем информацию таблицы в формат структурированной строки
                table_string = table_converter(table)
                # Добавляем строку таблицы в список
                text_from_tables.append(table_string)
                page_content.append(table_string)
                # Устанавливаем флаг True, чтобы избежать повторения содержимого
                table_extraction_flag = True
                # Преобразуем в другой элемент
                first_element = False
                # Добавляем условное обозначение в списки текста и формата
                page_text.append('table')
                line_format.append('table')

            # Проверяем, извлекли ли мы уже таблицы из этой страницы
            if element.y0 >= lower_side and element.y1 <= upper_side:
                pass
            elif i + 1 < len(page_elements) and not isinstance(page_elements[i + 1][1], LTRect):
                table_extraction_flag = False
                first_element = True
                table_num += 1


    # Создаём ключ для словаря
    dctkey = 'Page_'+str(pagenum)
    # Добавляем список списков как значение ключа страницы
    text_per_page[dctkey]= [page_text, line_format, text_from_images,text_from_tables, page_content]

# Закрываем объект файла pdf
pdfFileObj.close()

# Удаляем созданные дополнительные файлы
# os.remove('cropped_image.pdf')
# os.remove('PDF_image.png')

# Удаляем содержимое страницы
result = ''.join(text_per_page['Page_2'][4])
print(result)

стр. 3 ф. № 025/у

24. Записи врачей-специалистов:
03.03.2025
Дата осмотра
Врач (специальность)
Жалобы пациента
 на приеме, на дому, в фельдшерско-акушерском пункте, прочее.
|Назначения (исследования, консультации)|Лекарственные препараты, физиотерапия|
|ЭКГ с динамическим мониторингом – 10.03.25 в 17:00 в 223 кб|Бета-блокаторы, ингибиторы АПФ, рекомендации по фи- зической реабилитации.|
|Стресс-тест – 03.03.25 в 12:00 в 103 кб||
|Консультация по коррекции терапии – 03.03.25 в 15:00 в 301 кб||
|Листок нетрудоспособности, справка|Льготные рецепты|
|Выдан на 7 календарных дней.|Оформлены.|
|Информированное добровольное согласие на медицинское вмешательство, отказ от медицинского вмешательства Получено|None|
|Врач д-р Иванов С.С.|None|

In [ ]:
import re

# Регулярное выражение для поиска назначений
appointment_pattern = re.compile(
    r"Назначения \(исследования, консультации\).*?\n(\|.*\|.*\n(?!.*Листок нетрудоспособности.*\n)(\|.*\|\n)*)",  # Ищем таблицу, останавливаемся на "Листок нетрудоспособности"
    re.DOTALL  # Для поиска по многострочному тексту
)

# Поиск таблиц с назначениями
tables = appointment_pattern.findall(result)

# Обработка найденных таблиц
if tables:
    print("Найденные назначения:")
    for table in tables:
        # Извлекаем строки таблицы
        rows = table[0].strip().split("\n")
        for row in rows:
            # Убираем лишние пробелы и разделяем на ячейки
            cells = [cell.strip() for cell in row.split("|") if cell.strip()]
            # print(cells)
            # Проверяем, что строка содержит назначение (исключаем заголовок и лекарства)
            if "Листок нетрудоспособности" in cells[0]:
              break
            else:
                print(f"- {cells[0]}")
else:
    print("Таблицы с назначениями не найдены.")

Найденные назначения:
- ЭКГ с динамическим мониторингом – 10.03.25 в 17:00 в 223 кб
- Стресс-тест – 03.03.25 в 12:00 в 103 кб
- Консультация по коррекции терапии – 03.03.25 в 15:00 в 301 кб

In [ ]:
from gliner import GLiNER

# Загружаем мультиязычную модель
model = GLiNER.from_pretrained("urchade/gliner_medium-v2.1")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/transformers/convert_slow_tokenizer.py:559: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

In [ ]:
# Определяем типы сущностей для медицинского контекста
entities = ["кабинет", "место", "дата", "время", "процедура", "исследование", "назначение", "осмотр"]

# Применяем к вашему извлеченному тексту
res1 = model.predict_entities(result, entities, threshold=0.2)
for entity in res1:
    print(f"{entity['text']}: {entity['label']} (уверенность: {entity['score']})")

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

03.03.2025: дата (уверенность: 0.7007795572280884)
дому: место (уверенность: 0.48431137204170227)
фельдшерско-акушерском пункте: место (уверенность: 0.684027373790741)
Назначения: назначение (уверенность: 0.56630539894104)
исследования: исследование (уверенность: 0.5036203861236572)
консультации: процедура (уверенность: 0.49202123284339905)
физиотерапия: процедура (уверенность: 0.28983384370803833)
10.03.25: дата (уверенность: 0.5360618829727173)
17:00 в 223 кб: время (уверенность: 0.25354835391044617)
рекомендации по фи- зической реабилитации: процедура (уверенность: 0.2885376513004303)
Стресс-тест: процедура (уверенность: 0.3589041233062744)
03.03.25: дата (уверенность: 0.6498159766197205)
12:00 в 103 кб: время (уверенность: 0.2724400460720062)
Консультация по коррекции терапии: процедура (уверенность: 0.4498841464519501)
03.03.25: дата (уверенность: 0.6217949390411377)
15:00: время (уверенность: 0.41181573271751404)

In [ ]:
import re

# ---------- вспомогательные нормализации ----------
_norm_date = lambda t: re.search(r'\b(\d{2}\.\d{2}\.\d{2,4})\b', t)
_norm_time = lambda t: re.search(r'\b(\d{1,2}:\d{2})\b', t)
_norm_cab  = lambda t: re.search(r'(\d{1,4})\s*кб', t, flags=re.I)

# ---------- склейщик ----------
appointments, current = [], {}

for ent in res1:
    label, txt = ent['label'], ent['text']

    # новое назначение
    if label in ('процедура', 'исследование', 'осмотр'):
        if current and 'процедура' in current:   # сохраняем предыдущее
            appointments.append(current)
        current = {'процедура': txt, 'дата': '', 'время': '', 'кабинет': ''}

    # атрибуты
    elif label == 'дата' and not current.get('дата'):
        current['дата'] = _norm_date(txt).group(1) if _norm_date(txt) else txt
    elif label == 'время' and not current.get('время'):
        current['время'] = _norm_time(txt).group(1) if _norm_time(txt) else txt
    elif label in ('кабинет', 'место') and not current.get('кабинет'):
        current['кабинет'] = _norm_cab(txt).group(1) + ' кб' if _norm_cab(txt) else txt

# последнее
if current and 'процедура' in current:
    appointments.append(current)

# ---------- добираем время и кабинет, если GLiNER пропустил ----------
for ap in appointments:
    if 'процедура' not in ap:        # защита
        continue
    pos = result.find(ap['процедура'])
    if pos == -1:
        continue
    snippet = result[max(0, pos-60):pos+180]

    if not ap.get('время') and _norm_time(snippet):
        ap['время'] = _norm_time(snippet).group(1)
    if not ap.get('кабинет') and _norm_cab(snippet):
        ap['кабинет'] = _norm_cab(snippet).group(1) + ' кб'

# ---------- красивый вывод ----------
print('Найденные назначения:')
for ap in appointments:
    parts = [ap['процедура']]
    for fld in ('дата', 'время', 'кабинет'):
        if ap.get(fld):
            parts.append(ap[fld])
    print('- ' + ' – '.join(parts))

Найденные назначения:
- исследования – 17:00 – 223 кб
- консультации – 17:00 – 223 кб
- физиотерапия – 10.03.25 – 17:00 – 223 кб
- рекомендации по фи- зической реабилитации – 17:00 – 223 кб
- Стресс-тест – 03.03.25 – 12:00 – 103 кб
- Консультация по коррекции терапии – 03.03.25 – 15:00 – 103 кб

In [ ]:
import spacy

# Загружаем русскую модель
nlp = spacy.load("ru_core_news_lg")

# Обрабатываем текст
doc = nlp(result)

# Извлекаем сущности
for ent in doc.ents:
    print(f"{ent.text} - {ent.label_}")

АПФ - ORG
фи- - ORG
Получено|None| - ORG
Иванов - PER